import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import ContactFooter from "../Home/Footer";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <Link
            to="/"
            className="inline-flex items-center text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="w-5 h-5 mr-2" />
            Back to Home
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <article className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold text-gray-900 mb-8">
            Terms of Use
          </h1>

          <div className="bg-white rounded-lg shadow-sm p-6 sm:p-8 space-y-6">
            <p className="text-gray-600 leading-relaxed">
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules thereunder as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </p>

            <p className="text-gray-600 leading-relaxed">
              This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              guidelines) Rules, 2011 that require publishing the rules and
              regulations, privacy policy, and Terms of Use for access or usage
              of the website and/or Gumo mobile application.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">
              Basic Terms
            </h2>
            <div className="space-y-4">
              <p className="text-gray-600 leading-relaxed">
                You must be at least 18 years old and of firm competence to
                contract to use the Service.
              </p>
              <p className="text-gray-600 leading-relaxed">
                You are responsible for ensuring that in Your use of the
                Service, your action or omission is not contrary to any law for
                the time being in force. You are not allowed to post violent,
                discriminatory, plagiarized, promotional, unlawful, infringing,
                trolling, hateful Content via the Service. For the purposes of
                clarity, Content refers to any data, text, information,
                usernames, works of authorship, links and other content or
                materials, including information that the User posts and/or
                uploads onto the service, such as but not limited to the
                write-ups, photographs, graphics, videos, and any other
                information formats that may become shareable via the Service
                from time to time (collectively “Content”). You specifically
                undertake not to host, display, upload, modify, publish,
                transmit, update or share any information that –(a) belongs to
                another person and to which the user does not have any right to;
                (b) is grossly harmful, harassing, blasphemous, defamatory,
                obscene, pornographic, paedophilic, libellous, invasive of
                another’s privacy, hateful, or racially, ethnically
                objectionable, disparaging, relating to or encouraging money
                laundering or gambling, or otherwise unlawful in any manner
                whatever; (c) harms minors in any way; (d) infringes any patent,
                trademark, copyright or other proprietary rights; (e) violates
                any law for the time being in force; (f) deceives or misleads
                the addressee about the origin of such messages or communicates
                any information which is grossly offensive or menacing in
                nature; (g) impersonate another person; (h) contains software
                viruses or any other computer code, files or programs designed
                to interrupt, destroy or limit the functionality of any computer
                resource; (i) threatens the unity, integrity, defence, security
                or sovereignty of India, friendly relations with foreign states,
                or public order or causes incitement to the commission of any
                cognizable offence or prevents investigation of any offence or
                is insulting any other nation.
              </p>

              <div className="bg-gray-50 border-l-4 border-blue-500 p-4 my-6">
                <p className="text-sm text-gray-700">
                  <strong>Important:</strong> You are not allowed to post
                  violent, discriminatory, plagiarized, promotional, unlawful,
                  infringing, trolling, hateful Content via the Service.
                </p>
              </div>
            </div>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">
              General Terms
            </h2>
            <div className="space-y-4">
              <p className="text-gray-600 leading-relaxed">
                Gumo reserves the right to alter or terminate the Service or
                Your access to the Service for any reason, without notice, at
                any time, and without any liability to You. You can deactivate
                Your Gumo account at your discretion. If We terminate Your
                access to the Service or You delete Your account, Your Content,
                including work, comments, likes, friendships, and all other data
                will not be accessible to anyone (e.g., Users will not be able
                to navigate to Your username and view Your work). However, we
                may archive certain information, including Personal Information,
                and retain it as we may be required to do in order to fulfill
                our legal obligations. Gumo reserves the right, in our sole
                discretion, to change these Terms of Use (“Updated Terms”) from
                time to time. We may notify You before the Updated Terms become
                effective. You should review these updated Terms of Use prior to
                using Gumo. The Updated Terms will take effect from the time it
                is updated, or from sometime later as mentioned in the update.
                These Terms of Use will govern any disputes arising prior to the
                effective date of the Updated Terms. Gumo reserves the right to
                deny access to the Service to any User for any reason at any
                time. We may remove, edit, and/or monitor content or accounts we
                believe violate these Terms of Use. Gumo reserves the right to
                force forfeiture of any username, profile, or account for any
                reason at any time. Gumo is not responsible or liable for the
                conduct of any of its Users, be it online or offline. You will
                be responsible for Your interactions with other Gumo users on or
                off the Service. We reserve the right but we are not obliged to
                monitor or get involved in disputes between You and other users.
                A User should use his common sense and best judgment while
                interacting with other Gumo users. Your business dealings with
                third parties found on Gumo are solely between You and the third
                parties. You take responsibility for any and all data charges
                that incur on using Gumo. We prohibit crawling, scraping,
                caching, or otherwise accessing any Content on the Service via
                automated means, including but not limited to, user profiles and
                photos (except as may be the result of standard search engine
                protocols or technologies used by a search engine with Gumo’s
                express written consent). You further undertake to submit to the
                jurisdiction of courts at Bengaluru for any action arising from
                the breach of these Terms of Use, other Gumo Policies, violation
                of the IT Act and/or other laws, pursuant to Your usage or
                access of the Service.
              </p>
              <p className="text-gray-600 leading-relaxed">
                You can deactivate Your Gumo account at your discretion. If We
                terminate Your access to the Service or You delete Your account,
                Your Content, including work, comments, likes, friendships, and
                all other data will not be accessible to anyone.
              </p>
            </div>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">
              Rights
            </h2>
            <div className="space-y-4">
              <p className="text-gray-600 leading-relaxed">
                You must be at least 18 years old and of firm competence to
                contract to use the Service.
              </p>
              <p className="text-gray-600 leading-relaxed">
                Gumo does not claim ownership of any Content that a User posts
                on the Service. Instead, You hereby grant to Gumo a
                non-exclusive, fully paid and royalty-free, transferable,
                sub-licensable, worldwide license to use the Content that You
                post on or through the Service, subject to the Service’s Privacy
                Policy. You agree that: (i) You own the Content posted by You on
                Gumo or otherwise have the right to grant the right/licenses for
                it as set forth in these Terms of Use; (ii) Your Content must
                not infringe on the rights of other Users, including, without
                limiting to privacy and publicity rights, copyrights/trademark
                and/or other intellectual property rights. Gumo has content that
                is owned by Gumo (“Gumo Content”) and is protected by copyright,
                trademark, patent, and other relevant laws. You will not modify,
                remove, or conceal any copyright, trademark, service mark, or
                any other proprietary rights notice that accompanies Gumo
                Content. You will not reproduce, modify, adapt, prepare
                derivative works based on, display, distribute, publish,
                transmit, sell, license, or otherwise exploit the Gumo Content.
                Gumo’s name and logo are trademarks of Gumo and must not be
                copied or used, in whole or in part, without our prior written
                permission. In addition, custom graphics, all page headers,
                button icons, and scripts are service marks, trademarks, and/or
                trade dress of Gumo and must not be copied or used, in whole or
                in part, without prior written permission from Gumo. The Service
                may be interrupted for upgrades or scheduled maintenance, for
                emergency repairs, or due to failure of telecommunications links
                and/or equipment. We reserve the right to remove any Content
                from the Service for any reason, without prior notice. Content
                removed from the Service may continue to be stored by Gumo,
                including, without limitation, in order to comply with certain
                legal obligations, but may not be retrievable without a valid
                court order.
              </p>
              <div className="bg-gray-50 border-l-4 border-blue-500 p-4 my-6">
                <p className="text-sm text-gray-700">
                  <strong>Important:</strong> You are not allowed to post
                  violent, discriminatory, plagiarized, promotional, unlawful,
                  infringing, trolling, hateful Content via the Service.
                </p>
              </div>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Refunds
              </h3>
              <p className="text-gray-600">
              Refunds will be processed as per the property fare rules and cancellation policy. The processing time for refunds may vary depending on the mode of payment, bank etc. The refund will be credited to the same account from which the payment was made. For example, if the User used a credit card, Sociai Technologies Private Limited will make an appropriate charge reversal to the same credit card; like-wise if the User used a debit card, Sociai Technologies Private Limited will credit the money to the same debit card. In the event of cancellation and refund of partially utilized stays, upfront discount and promo code discount availed at the time of booking would be deducted from the refund amount.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Indemnity
              </h3>
              <p className="text-gray-600">
              You agree to indemnify, defend, and hold harmless Gumo, its officers, directors, employees, agents, licensors, and suppliers from and against all claims, liabilities, losses, expenses, damages, and costs, including reasonable attorneys’ fees, resulting from any violation of these Terms of Use or any activity related to Your account (including negligent or wrongful conduct) by You or any other person accessing the Service using Your account.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Disclaimer of Warranties
              </h3>
              <p className="text-gray-600">
              THE SERVICE, INCLUDING, WITHOUT LIMITATION, GUMO CONTENT, IS PROVIDED ON AN &quot;AS IS,&quot; &quot;AS AVAILABLE&quot; AND &quot;WITH ALL FAULTS&quot; BASIS. TO THE FULLEST EXTENT PERMISSIBLE BY LAW, NEITHER GUMO NOR ITS PARENT COMPANY, SUBSIDIARIES OR AFFILIATES MAKE ANY REPRESENTATIONS OR WARRANTIES OR ENDORSEMENTS OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, AS TO: (A) THE SERVICE; (B) THE GUMO CONTENT; (C) USER CONTENT; OR (D) SECURITY ASSOCIATED WITH THE TRANSMISSION OF INFORMATION TO GUMO OR VIA THE SERVICE. IN ADDITION, GUMO AND ITS PARENT COMPANY, SUBSIDIARIES AND AFFILIATES HEREBY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, SYSTEM INTEGRATION AND FREEDOM FROM COMPUTER VIRUS.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Limitation of Liability
              </h3>
              <p className="text-gray-600">
              UNDER NO CIRCUMSTANCES WILL GUMO, ITS PARENT COMPANY, SUBSIDIARIES, OR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF GUMO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), ARISING OUT OF, RELATING TO, OR IN ANY WAY CONNECTED WITH THE SERVICE OR THESE TERMS OF USE, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES OR LOSS ARISING OUT OF: (A) THE USE OF OR INABILITY TO USE THE SERVICE; (B) ANY CONTENT OR INFORMATION OBTAINED FROM OR THROUGH THE SERVICE; (C) ANY ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (D) PERSONAL INJURY OR PROPERTY DAMAGE OF ANY NATURE WHATSOEVER; (E) ANY UNAUTHORIZED ACCESS TO OR USE OF GUMO’S SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (F) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (G) ANY BUGS, VIRUSES, TROJAN HORSES OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH THE SERVICE; OR (H) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Termination
              </h3>
              <p className="text-gray-600">
              We reserve the right to terminate or suspend Your access to all or part of the Service at any time, with or without cause, with or without notice, effective immediately. If You wish to terminate Your Gumo account, You may do so by following the instructions on the Service or by contacting us at support@gumo.com.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Entire Agreement
              </h3>
              <p className="text-gray-600">
              These Terms of Use, together with the Privacy Policy and any other legal notices published by Gumo on the Service, shall constitute the entire agreement between You and Gumo concerning the Service. If any provision of these Terms of Use is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use, which shall remain in full force and effect.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
              Governing Law
              </h3>
              <p className="text-gray-600">
              These Terms of Use and any dispute or claim arising out of, or related to them, shall be governed by and construed in accordance with the laws of the State of California without giving effect to any choice or conflict of law provision or rule.
              </p>
            </div>
            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <h3 className="text-lg font-medium text-gray-900 mb-2">
                Contact Us
              </h3>
              <p className="text-gray-600">
                If you have any questions about these Terms, please contact us.
              </p>
            </div>
          </div>
        </article>
      </div>

      {/* Footer */}
      <footer className="bg-white border-t mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <p className="text-center text-gray-500 text-sm">
            © {new Date().getFullYear()} Gumo. All rights reserved.
          </p>
        </div>
      </footer>
      <ContactFooter/>
    </div>
  );
};

export default PrivacyPolicy;
